updateUrl = "https://vmct-cn.top/vault/update.txt"
downloadUrl = "https://vmct-cn.top/modpacks/vault/"
tipsUrl = "https://vmct-cn.top/tips.txt"
translationVersion = "2.4.4"
minutes = 25
packName = "VM汉化组模组汉化包1.18.zip"
packUrl= "https://cdn.modrinth.com/data/IDWIdXwS/versions/xCpjJgHS/VM汉化组模组汉化包1.18.zip"